{{- if and .Values.serviceAccount.create .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "visualization-api.fullname" . }}-role
  labels:
    {{- include "visualization-api.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  {{- with .Values.rbac.rules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "visualization-api.fullname" . }}-rolebinding
  labels:
    {{- include "visualization-api.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "visualization-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "visualization-api.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}